### ISSUE TITLE
Fails to open serial port

### ISSUE THREAD

**Issue by scramble45** [smart-home-technology/telit-modem#1]
This is the Error I get when trying the following code, also am I specify the baud rate correctly? - I am testing this against a Telit CE910-D Firmware : $FWREV: 18.12.001

**Error:**
    DEPRECATION: Please use `require('serialport')` instead of `require('serialport').SerialPort`
    Failed to open serial port Command {
    id: 1,
    state: 'timeout',
    result: { buf: <Buffer > },
    buf: 'ATE0',
    expectedResult: /^((ATE0\r\n\r\n)?)OK\r\n/,
    resultProcessor: [Function],
    timeout: undefined,
    _interval:
     Timeout {
       '0': null,
       _called: true,
       _idleTimeout: -1,
       _idlePrev: null,
       _idleNext: null,
       _idleStart: 1333,
       _onTimeout: null,
       _repeat: null } }
    Opened serial port
    enableSMS

**The code:**

```
var fs = require('fs'),
path = require('path'),
TelitModem = require('telit-modem');

var CREG = TelitModem.NetworkRegistrationStates;


var opts = {
           baudrate: 57600
           };

var modem = new TelitModem.TelitModem(opts);

modem.open('/dev/ttyUSB0').catch((err) => {
    console.error("Failed to open serial port", err);
}).then(() => {
    console.log("Opened serial port");

    process.on('SIGINT', function () {
        modem.unsubscribeFromNetworkRegistrationState();
        modem.closeGracefully(function(){
            process.exit(0);
        });
    });


    modem.startProcessing();

    modem.on('discarding', function(buf){
       console.log("discarding", buf.toString());
    });

    modem.subscribeToNetworkRegistrationState((state) => {
        switch(state){
            case CREG.NotRegisteredNotSearching:
                console.log("Network registration state: Not registered, not searching");
                break;

            case CREG.RegisteredHome:
                console.log('Network registration state: Registered (home network)');
                break;

            case CREG.NotRegisteredButSearching:
                console.log('Network registration state: Not registered, but searching');
                break;

            case CREG.RegistrationDenied:
                console.log('Network registration state: Registration denied');
                break;

            case CREG.Unknown:
                console.log('Network registration state: unknown');
                break;

            case CREG.RegisteredRoaming:
                console.log('Network registration state: Registered (roaming)');
                break;

        }
    });


    modem.enableSMS((pdu, destinationNumber, pduLen) => {
        console.log("Received SMS", destinationNumber, pduLen);
        console.log("Text", pdu.text.toString());
    });
});
```

**Comment by scramble45** [comment]
Well I had a typo on 'baudrate' should have been 'baudRate' and I got it to only say: Opened serial port - enableSMS but when I send a SMS nothing displays in the program output.

**Comment by tschiemer** [comment]
Hi there!

Ok, so I based the modem commands on the AT commands as specified in Telit_3G_Modules_AT_Commands_Reference_Guide_r10 which is targetted for the following modem families:
- HE-910
- UE-910
- UL-865
- UE-866-N3G
- UE-910-N3G

with FW version 12.00.xx7 - I've been developing on a HE910-D with FW 12.00.023. I should properly declare this in the readme, I think..

So I don't know if it could work with your modem of type CE910-D. To see into that I'd suggest having a look at the used commands yourself. The method's code is as follows ( https://github.com/smart-home-technology/telit-modem/blob/master/index.js#L168 ):

```
enableSMS(receiveCallback)
{
    // AT+CMGF=<mode> (0: PDU, 1: text)
    this.addCommand("AT+CMGF=0");

    //AT+CNMI=[<mode>[,<mt>[,<bm>[,<ds> [,<bfr>]]]]]
    // flush sms directly to modem
    this.addCommand("AT+CNMI=2,2");

    //+CMT: <alpha>,<length><CR><LF><pdu>
    this.addNotification('receivedSMS', /^\+CMT: "(.*)",(\d+)\r\n(.+)\r\n/, (buf, matches) => {
        // console.log(matches);
        receiveCallback(PDU.parse(matches[3]),matches[1], matches[2]);
    });

    console.log("enableSMS");
}
```

So it doesn't check for any failures (yet) and assumes everything goes smoothly. And as you see, essentially two commands are used to set the SMS presentation mode. Are these the same with your model? And when using only simple terminal session, do you get well formatted SMS notifications according to the regex?

**Comment by tschiemer** [comment]
Conclusion from email communication (by scramble45):

the used PDU package does not support 8bit PDU, so it fails when receiving such messages. it was suggested to use `node-pdu` instead
